#!/usr/bin/env bash

source ~/.config/info.sh
source ~/.config/sketchybar/pacman/colors.sh

### Store plugin and item directories in variables ###
ITEM_DIR="$HOME/.config/sketchybar/pacman/items" # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/pacman/plugins" # Directory where all the plugin scripts are stored

### Define defult font ###
FONT="Monocraft"

### Padding ###
PADDINGS=3  # All elements use this padidng

### Setting up the general bar appearance and default values ###
sketchybar \
  --bar \
    height=30 \
    corner_radius=14 \
    border_width=0 \
    margin=0 \
    blur_radius=0 \
    position=top \
    padding_left=0 \
    padding_right=0 \
    color="0x00000000" \
    topmost=off \
    sticky=on \
    font_smoothing=off \
    y_offset=0 \
    notch_width=0 \
  --default \
    drawing=on \
    updates=when_shown \
    icon.padding_left=$PADDINGS \
    icon.padding_right=$PADDINGS \
    label.padding_left=$PADDINGS \
    label.padding_right=$PADDINGS \
    background.padding_right=$PADDINGS \
    background.padding_left=$PADDINGS \

### Left ###
# . "$ITEM_DIR/apple_logo.sh" # apple logo
# . "$ITEM_DIR/system.sh" # resources monitor
# . "$ITEM_DIR/music_controls.sh" # apple music control widget
. "$ITEM_DIR/apple_music.sh" # playing on apple music

### Center ###
. "$ITEM_DIR/spaces.sh"    # workspaces

### Right ###
. "$ITEM_DIR/time.sh" # time
# . "$ITEM_DIR/sound.sh" # sound
. "$ITEM_DIR/battery.sh" # battery

echo "sketchybar configuation loaded.."
